In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.naive_bayes import GaussianNB

In [22]:
df = pd.read_csv("sonar.all-data.csv")
df.shape

(208, 61)

In [23]:
df.dtypes

Read1     float64
Read2     float64
Read3     float64
Read4     float64
Read5     float64
           ...
Read57    float64
Read58    float64
Read59    float64
Read60    float64
Label      object
Length: 61, dtype: object

In [24]:
labels = []
for i in df["Label"]:
    if i == 'R':
        labels.append(0)
    else: labels.append(1)


labels = pd.DataFrame(labels)
labels

     0
0    0
1    0
2    0
3    0
4    0
..  ..
203  1
204  1
205  1
206  1
207  1

[208 rows x 1 columns]

In [25]:
features = df.drop(["Label"], axis=1)
features

,Read1,Read2,Read3,Read4,Read5,Read6,Read7,Read8,Read9,Read10,...,Read51,Read52,Read53,Read54,Read55,Read56,Read57,Read58,Read59,Read60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0125,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0033,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0241,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0156,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0203,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0051,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0155,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0042,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0181,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115

In [41]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size=0.3, random_state=1)

train_features.reset_index(drop=True, inplace=True)
test_features.reset_index(drop=True, inplace=True)
train_labels.reset_index(drop=True, inplace=True)
test_labels.reset_index(drop=True, inplace=True)

In [42]:

model = GaussianNB()
model.fit(train_features, train_labels)

c:\users\rochi\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

GaussianNB()

In [46]:
predict_labels = model.predict(test_features)

predict_labels

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0],
      dtype=int64)

In [48]:
predict_labels = pd.DataFrame(predict_labels)
predict_labels

    0
0   1
1   0
2   0
3   1
4   0
.. ..
58  1
59  0
60  1
61  1
62  0

[63 rows x 1 columns]

In [50]:
acc = metrics.accuracy_score(test_labels, predict_labels)
acc

0.6031746031746031

In [51]:
prec = metrics.precision_score(test_labels, predict_labels)
prec

0.6842105263157895